services:
  app:
    container_name: api-usuarios
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL="postgresql+psycopg2://postgres:72942250@172.31.16.52:8005/bd_usuarios"
    networks:
      - internal_network
      
networks:
  internal_network:
    external: true