org: jhonchilo 
service: api-usuarios

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  region: us-east-1
  iam:
    role: arn:aws:iam::439947773262:role/LabRole 
  environment:
    USERS_TABLE: t_usuarios
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  register:
    handler: crear_usuario.register
    events:
      - httpApi:
          path: /register
          method: post

  login:
    handler: login_usuario.login
    events:
      - httpApi:
          path: /login
          method: post

  listUsers:
    handler: listar_usuarios.list_users
    events:
      - httpApi:
          path: /usuarios
          method: get

  getUser:
    handler: obtener_usuario.get_user
    events:
      - httpApi:
          path: /usuarios/{id}
          method: get

  updateUser:
    handler: modificar_usuario.update_user
    events:
      - httpApi:
          path: /usuarios/{id}
          method: put

  deleteUser:
    handler: eliminar_usuario.delete_user
    events:
      - httpApi:
          path: /usuarios/{id}
          method: delete

resources:
  Resources:
    UsuariosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: t_usuarios
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
