org: jhonchilo
service: api-usuarios

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::439947773262:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_usuarios
    ADMIN_EMAILS: "jhon.chilo@utec.edu.pe,sergio.delgado.a@utec.edu.pe,federico.iribar@utec.edu.pe"
    JWT_SECRET: "tu_clave_secreta_super_segura"

functions:
  crearUsuario:
    handler: crear_usuario.lambda_handler
    events:
      - http:
          path: /{tenant_id}/registro
          method: post
          cors: true
          integration: lambda

  loginUsuario:
    handler: login_usuario.lambda_handler
    events:
      - http:
          path: /{tenant_id}/login
          method: post
          cors: true
          integration: lambda

  listarUsuarios:
    handler: listar_usuarios.lambda_handler
    events:
      - http:
          path: /{tenant_id}/usuarios
          method: get
          cors: true
          integration: lambda

  obtenerUsuario:
    handler: obtener_usuario.lambda_handler
    events:
      - http:
          path: /{tenant_id}/usuarios/{usuario_id}
          method: get
          cors: true
          integration: lambda

  modificarUsuario:
    handler: modificar_usuario.lambda_handler
    events:
      - http:
          path: /{tenant_id}/usuarios/{usuario_id}
          method: put
          cors: true
          integration: lambda

  eliminarUsuario:
    handler: eliminar_usuario.lambda_handler
    events:
      - http:
          path: /{tenant_id}/usuarios/{usuario_id}
          method: delete
          cors: true
          integration: lambda

resources:
  Resources:
    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: usuario_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: usuario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
