org: jhonchilo
service: api-usuarios

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::439947773262:role/LabRole
  environment:
    TABLE_NAME: ${sls:stage}-t_usuarios
    ADMIN_EMAILS: "jhon.chilo@utec.edu.pe,sergio.delgado.a@utec.edu.pe,federico.iribar@utec.edu.pe"
    JWT_SECRET: "tu_clave_secreta_super_segura"

functions:
  crearUsuario:
    handler: crear_usuario.lambda_handler
    package:
      include:
        - crear_usuario.py
    events:
      - http:
          path: /usuarios/crear
          method: post
          cors: true

  eliminarUsuario:
    handler: eliminar_usuario.lambda_handler
    package:
      include:
        - eliminar_usuario.py
    events:
      - http:
          path: /usuarios/eliminar
          method: delete
          cors: true

  listarUsuarios:
    handler: listar_usuarios.lambda_handler
    package:
      include:
        - listar_usuarios.py
    events:
      - http:
          path: /usuarios/listar
          method: post
          cors: true

  obtenerUsuario:
    handler: obtener_usuario.lambda_handler
    package:
      include:
        - obtener_usuario.py
    events:
      - http:
          path: /usuarios/obtener
          method: post
          cors: true

  modificarUsuario:
    handler: modificar_usuario.lambda_handler
    package:
      include:
        - modificar_usuario.py
    events:
      - http:
          path: /usuarios/modificar
          method: put
          cors: true

  loginUsuario:
    handler: login_usuario.lambda_handler
    package:
      include:
        - login_usuario.py
    events:
      - http:
          path: /usuarios/login
          method: post
          cors: true

  verifyToken:
    handler: verify_token.lambda_handler
    package:
      include:
        - verify_token.py
    events:
      - http:
          path: /usuarios/verify
          method: get
          cors: true

resources:
  Resources:
    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: empresa
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: empresa
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
